#!/usr/bin/env bash

USERID=$UID

# Color PS1
echo -e '\nexport PS1="\[\033[38;5;82m\]\u@\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \\$ \[$(tput sgr0)\]"' | tee -a ~/.bashrc > /dev/null 2>&1
echo -e '\nexport PS1="\[\033[38;5;196m\]\u@\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \\$ \[$(tput sgr0)\]"' | sudo tee -a /root/.bashrc > /dev/null 2>&1

# Install some stuff
sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update && sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --assume-yes
sudo apt -y install docker-ce

# Get docker-compose
sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Add user to group docker
sudo usermod -aG docker ${USER}
GROUPID="$(cat /etc/group | grep docker | cut -d':' -f3)"

# Write some enviroments and create docker folder and set permissions
echo -e "\nPUID=$USERID\nPGID=$GROUPID\nTZ=\"Europe/Berlin\"\nUSERDIR=\"/home/$(whoami)/docker\"" | sudo tee -a /etc/environment > /dev/null 2>&1
mkdir ~/docker
sudo setfacl -Rdm g:docker:rwx ~/docker
sudo chmod -R 775 ~/docker

# Add Remote API for e.g. Portainer and reload daemon and docker
sudo sed -i '/lib/systemd/system/docker.service' -e "s/-H fd:\/\//-H fd:\/\/ -H tcp:\/\/0.0.0.0:2375/g"
sudo systemctl daemon-reload
sudo systemctl restart docker

echo -e "\nDone. Relogin for full functionality.\n" 
